export const ActionTypes = {
  // Login
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  // Login
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  // Signup
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  // Add Profile
  ADD_PROFILE_REQUEST: "ADD_PROFILE_REQUEST",
  ADD_PROFILE_SUCCESS: "ADD_PROFILE_SUCCESS",
  ADD_PROFILE_FAILURE: "ADD_PROFILE_FAILURE",

  // Get Profile
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",

  // Update Profile
  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  // Update Bio
  UPDATE_BIO_REQUEST: "UPDATE_BIO_REQUEST",
  UPDATE_BIO_SUCCESS: "UPDATE_BIO_SUCCESS",
  UPDATE_BIO_FAILURE: "UPDATE_BIO_FAILURE",

  // Add Post
  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",

  // Delete Post
  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",

  // Update Post
  UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",

  // Get Single Post
  GET_SINGLE_POST_REQUEST: "GET_SINGLE_POST_REQUEST",
  GET_SINGLE_POST_SUCCESS: "GET_SINGLE_POST_SUCCESS",
  GET_SINGLE_POST_FAILURE: "GET_SINGLE_POST_FAILURE",

  // Get All Post
  GET_ALL_POST_REQUEST: "GET_ALL_POST_REQUEST",
  GET_ALL_POST_SUCCESS: "GET_ALL_POST_SUCCESS",
  GET_ALL_POST_FAILURE: "GET_ALL_POST_FAILURE",

  // CLear Single Post
  CLEAR_POST: "CLEAR_POST",

  // Add Comment
  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",

  // Delete Comment
  DELETE_COMMENT_REQUEST: "DELETE_COMMENT_REQUEST",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAILURE: "DELETE_COMMENT_FAILURE",

  // Update Comment
  UPDATE_COMMENT_REQUEST: "UPDATE_COMMENT_REQUEST",
  UPDATE_COMMENT_SUCCESS: "UPDATE_COMMENT_SUCCESS",
  UPDATE_COMMENT_FAILURE: "UPDATE_COMMENT_FAILURE",

  //Load User
  LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAILURE: "LOAD_USER_FAILURE",
};
